"""add learning_item content field

Revision ID: 4ac63acc21f5
Revises: 25112801a2eb
Create Date: 2026-09-21 00:44:11.550532

"""
from alembic import op
import sqlalchemy as sa


revision = '4ac63acc21f5'
down_revision = '25112801a2eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_items', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_items', 'content')
    # ### end Alembic commands ###
